server:
  port: 8089
spring:
  application:
    name: gateway-api
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5433/fase3}
    username: ${DATASOURCE_USERNAME:application}
    password: ${DATASOURCE_PASSWORD:7KTu)$U9W1%7}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        default_schema: hospital
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
grpc:
  client:
    login-service:
      address: ${GRPC_AUTHENTICATION_API_URL:static://localhost:6565}
      negotiation-type: PLAINTEXT
    user-service:
      address: ${GRPC_AUTHENTICATION_API_URL:static://localhost:6565}
      negotiation-type: PLAINTEXT
    schedule-service:
      address: ${GRPC_SCHEDULE_API_URL:static://localhost:6566}
      negotiation-type: PLAINTEXT
    history-service:
      address: ${GRPC_HISTORICAL_API_URL:static://historical:6567}
      negotiation-type: PLAINTEXT