spring:
  application:
    name: schedule-api
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/hospital}
    username: ${DATASOURCE_USERNAME:application}
    password: ${DATASOURCE_PASSWORD:Xp8n9W3dLz6vQ1sE}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        default_schema: hospital
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  liquibase:
    change-log: classpath:liquibase/db/changelog/db.changelog-master.xml
    default-schema: hospital

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    enabled: true
    default-schema: hospital

grpc:
  server:
    port: 6566
    security:
      enabled: false