CREATE SCHEMA IF NOT EXISTS hospital AUTHORIZATION application;

GRANT USAGE ON SCHEMA hospital TO application;

ALTER DEFAULT PRIVILEGES IN SCHEMA hospital GRANT ALL ON TABLES TO application;
ALTER DEFAULT PRIVILEGES IN SCHEMA hospital GRANT ALL ON SEQUENCES TO application;